# SPDX-FileCopyrightText: 2026 UltimateKeys contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Pinned word-list sources. Every entry is verified against its SHA-256 before use.
# Rationale and license findings: docs/THIRD_PARTY.md and docs/adr/0008-dictionary-format.md.
# Bump dataVersion whenever any pin changes: installed copies are refreshed when it differs.

dataVersion=1
format=aosp-combined-gz
urlTemplate=https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/%s/dictionaries/%s?format=TEXT
commit=127336e9f29d69607eab55982324b210279ae8c5

languages=es,en

es.source=es_wordlist.combined.gz
es.sha256=889ad52bce2933e2a30a0560b8d5a76f5334500e776a7db7c7cb3e9e79fc2652

en.source=en_US_wordlist.combined.gz
en.sha256=0f78dd455b532be169a23f233227b811fabced4b5bd7fc9c40cc05839793bcbd
